name: Test
on:
  pull_request:
  push: 
    branches: [ "main" ]

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: SwiftFormat
        run: swiftformat --lint . --reporter github-actions-log

  test-macos:
    name: Test macOS using Xcode latest-stable
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v3
      - name: Run tests
        run: swift test -Xswiftc -warnings-as-errors -Xcc -Werror

  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: swift test -Xswiftc -warnings-as-errors -Xcc -Werror
