name: Test
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: "swift:6.1-noble"
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: swift format lint -r .

  test-macos:
    name: Test macOS using Xcode latest-stable
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v4
      - name: Run tests
        run: swift test -Xswiftc -warnings-as-errors -Xcc -Werror

  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: swift test -Xswiftc -warnings-as-errors -Xcc -Werror
